# Segunda clase (11/02/2018)

## Operadores relacionales

In [1]:
x <- 2
y <- 3

x + y    # Suma de x e y.
x - y    # Diferencia de x e y.
x * y    # Multiplicación de x e y.
x / y    # División de x e y.
x^y      # Alt + 94
x%%y     # Módulo o residuo. Son operaciones binarias.
x%/%y    # División de enteros. Son operaciones binarias.

# Los operadores binarios no lleva paréntesis.

#f(x,y,z) = # Hay dos maneras de declarar funciones en R.
# Comparaciómn matemática en R.
x; y # Se usa el punto y coma ';' para realizar dos acciones o más en una misma línea.
x < y
y > x
x <= y
y <= x
x == y
x != y
! x
x & y
x && y
x | y
x || y
xor(x,y)

[1] 5

[1] -1

[1] 6

[1] 0.6666667

## ¿Qué es un operador binario?



In [5]:
x = matrix(1:36, nrow = 6, ncol = 6); x
x[6,6] # Entrada seis y seis. Para digitar los corchetes prima `Alt + 91` y `Alt + 93`.
x[6,]  # Fila seis.
x[,6]  # Columna seis. 

# Observe que:

i <- matrix(c(1,1,2,2,3,3,4,4,5,5,6,6),6,2,byrow = T);i # No puedo usar 7, 7.
x[i] # He usado una matriz para llamar a otra matriz, es más preciso y complejo.
i
# Vamos a ver la indexación, llamando desde una matriz.

# i es una matriz y x es también es una matriz.

# ¿Qué es un cubo de datos en listas?

# byrow me indica que la carga sea por filas y el T nos indica que sea verdadero la carga por filas.
j <- matrix(c(1,6,2,5,3,4,4,3,5,2,6,1),6,2,byrow = T);j
x[j]

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1     7   13   19   25   31  
[2,] 2     8   14   20   26   32  
[3,] 3     9   15   21   27   33  
[4,] 4    10   16   22   28   34  
[5,] 5    11   17   23   29   35  
[6,] 6    12   18   24   30   36

[1] 36

[1]  6 12 18 24 30 36

[1] 31 32 33 34 35 36

[,1] [,2]
[1,] 1    1   
[2,] 2    2   
[3,] 3    3   
[4,] 4    4   
[5,] 5    5   
[6,] 6    6

[1]  1  8 15 22 29 36

[,1] [,2]
[1,] 1    1   
[2,] 2    2   
[3,] 3    3   
[4,] 4    4   
[5,] 5    5   
[6,] 6    6

[,1] [,2]
[1,] 1    6   
[2,] 2    5   
[3,] 3    4   
[4,] 4    3   
[5,] 5    2   
[6,] 6    1

[1] 31 26 21 16 11  6

In [3]:
x <- TRUE
y <- FALSE
mode(x); mode(y)
!x
x<-c(T,T,F,F)
y<-c(T,F,T,F)
x&y
xor # Muestra el código de la función `xor`. Con el teclado se seleecciona y oprime 'F1'.

[1] "logical"

[1] "logical"

[1] FALSE

[1]  TRUE FALSE FALSE FALSE

function (x, y) 
{
    (x | y) & !(x & y)
}
<bytecode: 0x5604d4d749c8>
<environment: namespace:base>

In [ ]:
x <- c(1,2,3,4,5)

(x>0) & (x<1)    # Entra un conjunto de respuestas.

(x>0) && (x<3)   # Entrega sola una respuesta.

y <- 2

(y>0) & (y<3)    # Entra un conjunto de respuestas.

(y>0) && (y<3)   # Entrega sola una respuesta.

z <- 5

(y>0) & (y<3)    # Entra un conjunto de respuestas.

(y>0) && (y<3)   # Entrega sola una respuesta.
                 # Entrega la primera respuesta.

x <- c(5,4,3,2,1)
(x>0) && (x<3)
                 #Mide la integridad de todo el grupo.

In [6]:
x <- c(1,2,3,4,5)

(x > 0) | (x < 3)

(x > 0) || (x < 3)

[1] TRUE TRUE TRUE TRUE TRUE

[1] TRUE

In [7]:
x <- TRUE
y <- FALSE
mode(x); mode(y)

!x
x <- c(T,T,F,F)
y <- c(T,F,T,F)
x&y

[1] "logical"

[1] "logical"

[1] FALSE

[1]  TRUE FALSE FALSE FALSE

In [8]:
#Creando un libro y una hoja de excel sin excel
setwd("C:/Users/usuario.pc/Desktop/10022018")
library(XLConnect)
lwb <- loadWorkbook("creando.xlsx",create = TRUE)
createSheet(lwb,name = "creandohoja") 
saveWorkbook(lwb)

# Escribiendo

ID <- 1:20
Alumno <- paste("cod", 1:20, sep = "_")
set.seed(100)
# La semilla va antes del runif

Notas <- runif(20, min=0, max=20) # 20 números aleatorios que varian desde el 0 hasta el 20
Notas <-round(Notas,0) # Se redondea con cero decimales y sobre escribimos.
bd <- data.frame(ID,Alumno,Notas); bd

lwb <- loadWorkbook("bdescribir.xlsx", create = TRUE)# Se prefiere no usar comillas, ni caracteres especiales acentos, utf8 no acepta tildes.
createSheet(lwb,name="notascurso")
createName(lwb,name="notascurso", formula= "notascurso!$A$1")
writeNamedRegion(lwb,bd,name="notascurso")
saveWorkbook(lwb)
# Todo lo que se puede hacer en Excel se puede hacer en R.
#Un punto semilla, En R podemos dominar el punto inicial.

ERROR: Error in setwd("C:/Users/usuario.pc/Desktop/10022018"): no es posible cambiar el directorio de trabajo


## Función  Set Working Directory `setwd()`


In [10]:
help(setwd)

Cuando usamos incorrectamente `&&`en lugar de `&` para este tipo de casos, R simplemente evalúa los primeros resultados de los vectores lógicos e ignora el resto. En general `&&` es pereferido por el control de flujo, es decir, el uso de los condicionales `if` o `while`.

In [32]:
rm(list=ls()) # Borrar todas las variables, si se desea limpiar la variables antes de usar: remove('x'),
x <- rbinom(100,5,0.80)
x[(x>1)&(x<3)]

[1] 2 2 2

### Aplicación

¿Cuál sería el resultado de ejecutar las siguientes instrucciones?

In [ ]:
x = c(1,3,5,7,9)      # Guarda en memoria.
y = c(2,3,5,7,11,13)

x + 1                 # Muestra un vector con cada elemento aumentado en 1.
y * 2                 # Muestra otro vector con cada elemento multiplicado por 2.
length(x); length(y)  # Muestra la cantidad de columnas del vector x. Análogamente con y.
x + y                 # Muestra un vector con cada elemento la suma de los elemento de x e y.
sum(x>5); sum(x[x>5]) # Primero obtiene como valor lógico y luego lo suma, es decir,
                      #1+1=2. En el otro caso suma los valores 7 y 9 da 16.

sum(x>5|x<3)          # "|" se lee o "&" se lee y.
y[3]
y[-3]
y[x]
y[y>=7]               # Con el operador 'as.numeric()'
                      # Cuando es corchete, se llama a una matriz, es un arreglo numérico indexado, se le puede llamar a su posición.

In [33]:
memory.profile()

NULL      symbol    pairlist     closure environment     promise 
          1        9878      233359        4882        1116        6864 
   language     special     builtin        char     logical     integer 
      66438          45         671       11995        9364       43446 
     double     complex   character         ...         any        list 
       3189           1       59406           5           0       21051 
 expression    bytecode externalptr     weakref         raw          S4 
          2       17127        2161         570         579        1159

In [34]:
gc()

used   (Mb) gc trigger (Mb) max used (Mb)
Ncells 493407 26.4  940480    50.3  750400  40.1
Vcells 941513  7.2 1916981    14.7 1191645   9.1

## Ejercicio de aplicación (Diapositiva de clase)

<img style="float" src="../images/aplication.png" width="850">

In [5]:
x = c(1,3,5,7,9)     # Vector x de 5 elementos. No se imprime en consola.
y = c(2,3,5,7,11,13) # Vector y de 6 elementos. No se imprime en consola.
x+1                  # Vector con coordenadas de x aumentadas en uno.
y*2                  # Vector con coordenadas de y multiplicadas por dos.
length(x)            # Muestra la cantidad de entradas de x.
length(y)            # Muestra la cantidad de entradas de x
x + y                # Operación no compatible. (Warning)
# Prevalece la longitud de y, adapta el vector x con 6 componentes, repitiendo el término 6 de x con el primero de x y efectúa la operación.
sum(x>5) # El arguemto de `sum` es 0 o 1, la suma es 2.
sum(x[x>5]) # Suma las entradas de x mayores que cinco.
sum(x>5 | x< 3)      # Suma 0 o 1 según la condición, la suma da 16.
y[3]                 # Imprime la tercera componente de y.
y[-3]                # Imprime el vector y, excluyendo la tercera componente.
y[x]                 # Imprime las entradas de y que tengan los índices de las entradas de x.
y[y>=7]              # Imprime un vector con todas las entradas mayores o iguales que siete.

[1]  2  4  6  8 10

[1]  4  6 10 14 22 26

[1] 5

[1] 6

Warning message in x + y:
“longitud de objeto mayor no es múltiplo de la longitud de uno menor”

[1]  3  6 10 14 20 14

[1] 2

[1] 16

[1] 3

[1] 5

[1]  2  3  7 11 13

[1]  2  5 11 NA NA

[1]  7 11 13

## Otro ejercicio de aplicación

In [6]:
# Cuando usamos incorrectamente && en lugar de & para este tipo de casos, R 
# simplemente evalúa los primeros elementos de los vectores lógicos e ignora 
# el resto. En general && es preferido para el control de flujo, es decir, el 
# uso de los condicionales if o while. 
x <- rbinom(100,5,0.80)
x[(x > 1) & (x < 3)]

if (any(x == 1) && any(x == 6)){}else "V y F = F"
if (any(x == 1) || any(x == 6)) "V o F = V"


[1] 2 2 2 2 2

[1] "V y F = F"

[1] "V o F = V"