# Segunda clase (10/02/2018)

## Variables y tipos de datos

R soporta como tipo de datos básicos valores numéricos, caracteres, cadenas de caracteres y valores booleanos.

### Vectores

Es una concatenación de una colección de datos del mismo tipo.

In [8]:
v1 <- c(1,0,0); v1
v2 <- c(0,1,0); v2
v3 <- c(0,0,1); v3

[1] 1 0 0

[1] 0 1 0

[1] 0 0 1

### Matrices

Es una colección de datos del mismo tipo que tiene dos dimensiones.

In [12]:
M <- matrix(1:10, nrow = 2, ncol = 5); M

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [14]:
help (dim) # Función dim, para hallar la dimensión de un vector, matriz.

## Operaciones lógico - aritméticas

In [64]:
printf <- function(...) cat(sprintf(...)) # La hermosa función printf.
x <- 2; y <- 3;
suma = x + y
diferencia = x - y
producto = x * y
cociente = x / y
potencia = x^y    # Teclas: Alt + 94
residuo = x%%y    # Módulo o residuo. Son operaciones binarias.
diventera = x%/%y # División de enteros. Son operaciones binarias.
printf("La suma de x e y es %d.\nLa diferencia de x e y es %d.\n", suma, diferencia)
printf("El producto de x e y es %d.\nEl cociente de x e y es %.2f\n", producto, cociente)
printf("La potencia de x a la y es %d.\nx módulo y es %d.\n", potencia, residuo)
printf("La división entera de x con y es %d.\n",diventera)
printf("El techo de x es %d y el piso de y es %d.\n", ceiling(x), floor(y))
printf("El valor de pi truncado es %d.\n", trunc(pi))
round(x, digits = 0)
signif(x, digits = 6)

La suma de x e y es 5.
La diferencia de x e y es -1.
El producto de x e y es 6.
El cociente de x e y es 0.67
La potencia de x a la y es 8.
x módulo y es 2.
La división entera de x con y es 0.
El techo de x es 2 y el piso de y es 3.
El valor de pi truncado es 3.


[1] 2

[1] 2

In [17]:
#f(x,y,z) = # Hay dos maneras de declarar funciones en R.
# Comparaciómn matemática en R.
x; y # Se usa el punto y coma ';' para realizar dos acciones o más en una misma línea.
x < y
y > x
x <= y
y <= x
x == y
x != y
! x
x & y
x && y
x | y
x || y
xor(x,y)

[1] 2

[1] 3

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

## ¿Qué es un operador binario?

Los operadores binarios no lleva paréntesis.

Las operaciones de comparación en R se escriben con los siguientes operadores:

- Mayor que: `>`
- Mayor o igual que: `>=`
- Menor que: `<`
- Menor o igual que: `<=`
- Igual a: `==`
- Distinto de: `!=`

Estas operaciones devuelven un valor lógico `TRUE` o `FALSE`.

Por ejemplo:

In [70]:
a <- 10; b <- 8
a > 5
b >= 3
a < b
a <= 10
a == 5
b != a

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

Algunas funciones útiles con vectores son:

- Longitud o número de elementos: `length()`
- Mínimo y máximo: `min()`, `max()`
- Índices del valor máximo y mínimo: `which.max()`, `which.min()`
- Suma de los elementos o conteo de `TRUE`s: `sum()`
- Media y mediana: `mean()`, `median()`

Por ejemplo:

In [71]:
v <- c(5,10,0,0,2)
length(v)
min(v)
max(v)
which.min(v)
which.max(v)
sum(v)
mean(v)
median(v)

[1] 5

[1] 0

[1] 10

[1] 3

[1] 2

[1] 17

[1] 3.399999999999999911182

[1] 2

In [5]:
x = matrix(1:36, nrow = 6, ncol = 6); x
x[6,6] # Entrada seis y seis. Para digitar los corchetes prima `Alt + 91` y `Alt + 93`.
x[6,]  # Fila seis.
x[,6]  # Columna seis. 

# Observe que:

i <- matrix(c(1,1,2,2,3,3,4,4,5,5,6,6),6,2,byrow = T);i # No puedo usar 7, 7.
x[i] # He usado una matriz para llamar a otra matriz, es más preciso y complejo.
i
# Vamos a ver la indexación, llamando desde una matriz.

# i es una matriz y x es también es una matriz.

# ¿Qué es un cubo de datos en listas?

# byrow me indica que la carga sea por filas y el T nos indica que sea verdadero la carga por filas.
j <- matrix(c(1,6,2,5,3,4,4,3,5,2,6,1),6,2,byrow = T);j
x[j]

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1     7   13   19   25   31  
[2,] 2     8   14   20   26   32  
[3,] 3     9   15   21   27   33  
[4,] 4    10   16   22   28   34  
[5,] 5    11   17   23   29   35  
[6,] 6    12   18   24   30   36

[1] 36

[1]  6 12 18 24 30 36

[1] 31 32 33 34 35 36

[,1] [,2]
[1,] 1    1   
[2,] 2    2   
[3,] 3    3   
[4,] 4    4   
[5,] 5    5   
[6,] 6    6

[1]  1  8 15 22 29 36

[,1] [,2]
[1,] 1    1   
[2,] 2    2   
[3,] 3    3   
[4,] 4    4   
[5,] 5    5   
[6,] 6    6

[,1] [,2]
[1,] 1    6   
[2,] 2    5   
[3,] 3    4   
[4,] 4    3   
[5,] 5    2   
[6,] 6    1

[1] 31 26 21 16 11  6

In [3]:
x <- TRUE
y <- FALSE
mode(x); mode(y)
!x
x<-c(T,T,F,F)
y<-c(T,F,T,F)
x&y
xor # Muestra el código de la función `xor`. Con el teclado se seleecciona y oprime 'F1'.

[1] "logical"

[1] "logical"

[1] FALSE

[1]  TRUE FALSE FALSE FALSE

function (x, y) 
{
    (x | y) & !(x & y)
}
<bytecode: 0x5604d4d749c8>
<environment: namespace:base>

In [ ]:
x <- c(1,2,3,4,5)

(x>0) & (x<1)    # Entra un conjunto de respuestas.

(x>0) && (x<3)   # Entrega sola una respuesta.

y <- 2

(y>0) & (y<3)    # Entra un conjunto de respuestas.

(y>0) && (y<3)   # Entrega sola una respuesta.

z <- 5

(y>0) & (y<3)    # Entra un conjunto de respuestas.

(y>0) && (y<3)   # Entrega sola una respuesta.
                 # Entrega la primera respuesta.

x <- c(5,4,3,2,1)
(x>0) && (x<3)
                 #Mide la integridad de todo el grupo.

In [6]:
x <- c(1,2,3,4,5)

(x > 0) | (x < 3)

(x > 0) || (x < 3)

[1] TRUE TRUE TRUE TRUE TRUE

[1] TRUE

In [7]:
x <- TRUE
y <- FALSE
mode(x); mode(y)

!x
x <- c(T,T,F,F)
y <- c(T,F,T,F)
x&y

[1] "logical"

[1] "logical"

[1] FALSE

[1]  TRUE FALSE FALSE FALSE

In [8]:
#Creando un libro y una hoja de excel sin excel
setwd("C:/Users/usuario.pc/Desktop/10022018")
library(XLConnect)
lwb <- loadWorkbook("creando.xlsx",create = TRUE)
createSheet(lwb,name = "creandohoja") 
saveWorkbook(lwb)

# Escribiendo

ID <- 1:20
Alumno <- paste("cod", 1:20, sep = "_")
set.seed(100)
# La semilla va antes del runif

Notas <- runif(20, min=0, max=20) # 20 números aleatorios que varian desde el 0 hasta el 20
Notas <-round(Notas,0) # Se redondea con cero decimales y sobre escribimos.
bd <- data.frame(ID,Alumno,Notas); bd

lwb <- loadWorkbook("bdescribir.xlsx", create = TRUE)# Se prefiere no usar comillas, ni caracteres especiales acentos, utf8 no acepta tildes.
createSheet(lwb,name="notascurso")
createName(lwb,name="notascurso", formula= "notascurso!$A$1")
writeNamedRegion(lwb,bd,name="notascurso")
saveWorkbook(lwb)
# Todo lo que se puede hacer en Excel se puede hacer en R.
#Un punto semilla, En R podemos dominar el punto inicial.

ERROR: Error in setwd("C:/Users/usuario.pc/Desktop/10022018"): no es posible cambiar el directorio de trabajo


## Función  Set Working Directory `setwd()`


In [10]:
help(setwd)

Cuando usamos incorrectamente `&&`en lugar de `&` para este tipo de casos, R simplemente evalúa los primeros resultados de los vectores lógicos e ignora el resto. En general `&&` es pereferido por el control de flujo, es decir, el uso de los condicionales `if` o `while`.

In [32]:
rm(list=ls()) # Borrar todas las variables, si se desea limpiar la variables antes de usar: remove('x'),
x <- rbinom(100,5,0.80)
x[(x>1)&(x<3)]

[1] 2 2 2

### Aplicación

¿Cuál sería el resultado de ejecutar las siguientes instrucciones?

In [ ]:
x = c(1,3,5,7,9)      # Guarda en memoria.
y = c(2,3,5,7,11,13)

x + 1                 # Muestra un vector con cada elemento aumentado en 1.
y * 2                 # Muestra otro vector con cada elemento multiplicado por 2.
length(x); length(y)  # Muestra la cantidad de columnas del vector x. Análogamente con y.
x + y                 # Muestra un vector con cada elemento la suma de los elemento de x e y.
sum(x>5); sum(x[x>5]) # Primero obtiene como valor lógico y luego lo suma, es decir,
                      #1+1=2. En el otro caso suma los valores 7 y 9 da 16.

sum(x>5|x<3)          # "|" se lee o "&" se lee y.
y[3]
y[-3]
y[x]
y[y>=7]               # Con el operador 'as.numeric()'
                      # Cuando es corchete, se llama a una matriz, es un arreglo numérico indexado, se le puede llamar a su posición.

In [33]:
memory.profile()

NULL      symbol    pairlist     closure environment     promise 
          1        9878      233359        4882        1116        6864 
   language     special     builtin        char     logical     integer 
      66438          45         671       11995        9364       43446 
     double     complex   character         ...         any        list 
       3189           1       59406           5           0       21051 
 expression    bytecode externalptr     weakref         raw          S4 
          2       17127        2161         570         579        1159

In [34]:
gc()

used   (Mb) gc trigger (Mb) max used (Mb)
Ncells 493407 26.4  940480    50.3  750400  40.1
Vcells 941513  7.2 1916981    14.7 1191645   9.1

## Ejercicio de aplicación (Diapositiva de clase)

<img style="float" src="../images/aplication.png" width="850">

In [5]:
x = c(1,3,5,7,9)     # Vector x de 5 elementos. No se imprime en consola.
y = c(2,3,5,7,11,13) # Vector y de 6 elementos. No se imprime en consola.
x+1                  # Vector con coordenadas de x aumentadas en uno.
y*2                  # Vector con coordenadas de y multiplicadas por dos.
length(x)            # Muestra la cantidad de entradas de x.
length(y)            # Muestra la cantidad de entradas de x
x + y                # Operación no compatible. (Warning)
# Prevalece la longitud de y, adapta el vector x con 6 componentes, repitiendo el término 6 de x con el primero de x y efectúa la operación.
sum(x>5) # El arguemto de `sum` es 0 o 1, la suma es 2.
sum(x[x>5]) # Suma las entradas de x mayores que cinco.
sum(x>5 | x< 3)      # Suma 0 o 1 según la condición, la suma da 16.
y[3]                 # Imprime la tercera componente de y.
y[-3]                # Imprime el vector y, excluyendo la tercera componente.
y[x]                 # Imprime las entradas de y que tengan los índices de las entradas de x.
y[y>=7]              # Imprime un vector con todas las entradas mayores o iguales que siete.

[1]  2  4  6  8 10

[1]  4  6 10 14 22 26

[1] 5

[1] 6

Warning message in x + y:
“longitud de objeto mayor no es múltiplo de la longitud de uno menor”

[1]  3  6 10 14 20 14

[1] 2

[1] 16

[1] 3

[1] 5

[1]  2  3  7 11 13

[1]  2  5 11 NA NA

[1]  7 11 13

## Otro ejercicio de aplicación

In [6]:
# Cuando usamos incorrectamente && en lugar de & para este tipo de casos, R 
# simplemente evalúa los primeros elementos de los vectores lógicos e ignora 
# el resto. En general && es preferido para el control de flujo, es decir, el 
# uso de los condicionales if o while. 
x <- rbinom(100,5,0.80)
x[(x > 1) & (x < 3)]

if (any(x == 1) && any(x == 6)){}else "V y F = F"
if (any(x == 1) || any(x == 6)) "V o F = V"


[1] 2 2 2 2 2

[1] "V y F = F"

[1] "V o F = V"

In [68]:
## Calculate PI with R.
options(digits = 22) # 22 is max allowed
pi_calc <- 3
x <- 2
n <- 10000

for(i in 1:n) {
y <- x + 1
z <- x + 2
combine_with_pi_calc <- 4 / (x * y * z)
test <- i %% 2 == 0 
if (isTRUE(test)) {
 pi_calc <- pi_calc - combine_with_pi_calc
}
else {
 pi_calc <- pi_calc + combine_with_pi_calc
}

x <- z
print(pi_calc)
}

# Compare to the pi constant included in R
# Matches out to the 12th digit
# I think the error is due to floating point, not the formula, but I'm not sure.
print(pi)

[1] 3.166666666666666518637
[1] 3.133333333333333303727
[1] 3.145238095238095166195
[1] 3.139682539682539630377
[1] 3.142712842712842569171
[1] 3.140881340881340744176
[1] 3.142071817071816930422
[1] 3.141254823607764645743
[1] 3.141839618929402000447
[1] 3.141406718496501770943
[1] 3.141736099260665326938
[1] 3.141479689004254893803
[1] 3.14168318920775524461
[1] 3.141518985595275648137
[1] 3.141653394197426063528
[1] 3.141541985997782671092
[1] 3.141635356679388646484
[1] 3.141556330284572595701
[1] 3.141623806667838358919
[1] 3.141565734658546826807
[1] 3.141616071918186481327
[1] 3.141572154482964673861
[1] 3.141610699040473075883
[1] 3.141576685435031102145
[1] 3.141606851347550133369
[1] 3.14157997396218213737
[1] 3.141604023986232174792
[1] 3.141582418247748087481
[1] 3.141601900032279459651
[1] 3.141584272674620592625
[1] 3.141600273698686329737
[1] 3.141585704934117373455
[1] 3.14159900740571673694
[1] 3.141586828621159455111
[1] 3.141598006801351594675
[1] 3.14158772254449214

[1] 3.141592653589793115998
